/*
 * Translations from the guvcview Spanish translation team (https://translations.launchpad.net/guvcview/trunk/+pots/guvcview/es/+translate)
 * License: GPLv3
 */
const Translation = {
	"$t": function(string) {
		return Translation[string] || string;
	},
	"Disabled": "Deshabilitado",
	//"": "Project-Id-Version: es\nReport-Msgid-Bugs-To: pj.assis@gmail.com\nPOT-Creation-Date: 2014-08-17 22:49+0100\nPO-Revision-Date: 2013-02-25 05:38+0000\nLast-Translator: Adolfo Jayme <fitoschido@gmail.com>\nLanguage-Team: Portuguese <pt@li.org>\nLanguage: pt\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\nX-Launchpad-Export-Date: 2013-12-08 10:36+0000\nX-Generator: Launchpad (build 16869)\n",
	// "guvcview": "guvcview",
	// "GTK UVC video viewer": "Reproductor video GTK UVC",
	// "A video viewer and capturer for the linux uvc driver": "Un reproductor y capturador de vídeo para el controlador uvc de Linux",
	// "capture video from v4l2 devices": "",
	// "Video capture tool for video4linux2 compliant cameras, with special emphasis on the linux uvc driver. It provides Image (jpg, png, bmp) and Video (mjpeg, flv1, wmv1, mpg2, mpg4,...) capture with sound in several formats( currently: avi and matroska). I also supports a control panel option (--control_only) that is compatible with any other v4l2 app.": "",
	// "User Controls": "Controles de usuario",
	"Brightness": "Brillo",
	"Contrast": "Contraste",
	"Hue": "Matiz",
	"Saturation": "Saturación",
	"Sharpness": "Nitidez",
	"Gamma": "Gamma",
	"Backlight Compensation": "Compensación de retroiluminación",
	"Power Line Frequency": "Frecuencia de la línea eléctrica",
	"Hue, Automatic": "Matiz, automático",
	"Focus, Auto": "Foco, Auto",
	"Manual Mode": "Modo manual",
	"Auto Mode": "Modo automático",
	"Shutter Priority Mode": "Modo prioridad del obturador",
	"Aperture Priority Mode": "Modo prioridad de la abertura",
	"Black Level": "Nivel de negros",
	"White Balance, Automatic": "Balance de blancos, automático",
	"Do White Balance": "Hacer balance de blancos",
	"Red Balance": "Balance de rojos",
	"Blue Balance": "Balance de azules",
	"Exposure": "Exposición",
	"Gain, Automatic": "Ganancia, automático",
	"Gain": "Ganancia",
	"Horizontal Flip": "Giro horizontal",
	"Vertical Flip": "Giro vertical",
	"Horizontal Center": "Centrado horizontal",
	"Vertical Center": "Centrado vertical",
	"Chroma AGC": "AGC de croma",
	"Color Killer": "Anulador de color",
	"Color Effects": "Efectos de color",
	"Camera Controls": "Controles de cámara",
	"Auto Exposure": "Exposición automática",
	"Exposure Time, Absolute": "Tiempo de exposición, absoluto",
	"Exposure, Dynamic Framerate": "Exposición, tasa de fotogramas dinámica",
	"Pan, Relative": "",
	"Tilt, Relative": "",
	"Pan, Reset": "",
	"Tilt, Reset": "",
	"Pan, Absolute": "",
	"Focus, Absolute": "Enfoque, Absoluto",
	"Focus, Relative": "Enfoque, relativo",
	"Focus, Automatic": "Enfoque, automático",
	"Zoom, Absolute": "Zoom, absoluto",
	"Zoom, Relative": "Zoom, relativo",
	"Zoom, Continuous": "Zoom, continuo",
	"Privacy": "Privacidad",
	"Exposure, Auto": "Exposición, auto",
	"Exposure, Auto Priority": "Exposición, Prioridad Auto",
	"Exposure (Absolute)": "Exposición (Absoluta)",
	"White Balance Temperature, Auto": "Equilibrio blanco, auto",
	"White Balance Temperature": "Blanco (Temp. de color)",
	"White Balance Component, Auto": "Componente de color, Auto",
	"White Balance Blue Component": "Componente Azul",
	"White Balance Red Component": "Componente Rojo",
	"Focus": "Enfoque",
	"Focus (Absolute)": "Enfoque (absoluto)",
	"Off": "Apagado",
	"On": "Encendido",
	"Blinking": "Parpadeo",
	"Auto": "Auto",
	"Pan (relative)": "Rotación (relativo)",
	"Tilt (relative)": "Inclinación (relativa)",
	"Pan Reset": "Rotación (reajuste)",
	"Tilt Reset": "Inclinación (reajuste)",
	"Focus (absolute)": "Foco (absoluto)",
	"LED1 Mode": "Modo LED1",
	"LED1 Frequency": "Frecuencia LED1",
	// "Disable video processing": "Parar el proceso de vídeo",
	// "Raw bits per pixel": "Bits por pixel (Raw)",
	// "PCM - uncompressed (float 32 bit)": "PCM - sin compresión (16 bit)",
	// "MP2 (MPEG audio layer 2)": "",
	// "MP3 (MPEG audio layer 3)": "",
	// "AC-3 (ATSC A/52A)": "",
	// "AAC (Advanced Audio Coding)": "",
	// "Vorbis": "",
	// "Raw camera input": "Salida de la cámara:",
	// "MJPG - compressed": "MJPG - comprimido",
	// "MPEG video 1": "MPEG video 1",
	// "FLV1 - flash video 1": "FLV1 - flash video 1",
	// "WMV1 - win. med. video 7": "WMV1 - win. med. video 7",
	// "MPG2 - MPG2 format": "MPG2 - MPG2 format",
	// "MS MP4 V3": "MS MP4 V3",
	// "MPEG4-ASP": "MPEG4-ASP",
	// "MPEG4-AVC (H264)": "MPEG4-AVC (H264)",
	// "VP8 (VP8)": "",
	// "Theora (ogg theora)": "",
	// "Audio API:": "Audio API",
	// "NO SOUND": "",
	// "PORTAUDIO": "PORTAUDIO",
	// "PULSEAUDIO": "PULSEAUDIO",
	// "Input Device:": "Dispositivo de entrada:",
	// "Sample Rate:": "Sample Rate:",
	// "Dev. Default": "Automático",
	// "Channels:": "Canales:",
	// "1 - mono": "1 - mono",
	// "2 - stereo": "2 - stereo",
	// "---- Audio Filters ----": "---- Filtros Video ----",
	// " Echo": " Eco",
	// " Reverb": " Reverb",
	// " Fuzz": " Ruido",
	// " WahWah": " WahWah",
	// " Ducky": " Pato",
	// "Stop Video (V)": "Detener vídeo (V)",
	// "Cap. Video (V)": "Cap. vídeo (V)",
	// "Error": "Error",
	// "_Ok": "",
	// "_Cancel": "cancelar",
	// "\nYou have more than one video device installed.\nDo you want to try another one ?\n": "",
	// "Device:": "Dispositivo de entrada:",
	// "Guvcview Video Capture": "Captura de vídeo Guvcview",
	// "Guvcview": "guvcview",
	// "Stop Cap. (I)": "Detener auto (I)",
	// "Cap. Image (I)": "Cap. imagen (I)",
	// "_Quit": "",
	// "Image Controls": "Controles de la imagen",
	// "H264 Controls": "Controles de usuario",
	// "Video Controls": "Controles de usuario",
	// "Audio Controls": "Controles de usuario",
	// "Save Profile": "",
	// "_Save": "",
	// "Load Profile": "",
	// "_Open": "",
	// "File Format:": "",
	// "gpfl  (*.gpfl)": "",
	// "any (*.*)": "",
	// "Photo file name": "Archivo de Imagen",
	// "Raw  (*.raw)": "",
	// "Jpeg (*.jpg)": "",
	// "Png  (*.png)": "",
	// "Bmp  (*.bmp)": "",
	// "Video file name": "Archivo de Imagen",
	// "Matroska  (*.mkv)": "",
	// "WebM (*.webm)": "",
	// "Avi  (*.avi)": "",
	// "start new": "Comenzar nuevo",
	// "restart": "Recomenzar aplicación",
	// "new": "nuevo",
	// "cancel": "cancelar",
	// "launch new process or restart?.\n\n": "nuevo proceso o recomenzar?\n\n",
	// "video codec values": "valores de codec de audio",
	// "_OK": "",
	// "                              encoder fps:   \n (0 - use fps combobox value)": "",
	// " monotonic pts": "",
	// "bit rate:   ": "media de bits:   ",
	// "qmax:   ": "qmáx:   ",
	// "qmin:   ": "qmin:   ",
	// "max. qdiff:   ": "máx. qdiff:   ",
	// "dia size:   ": "tamaño dia:   ",
	// "pre dia size:   ": "tamaño pre dia:   ",
	// "pre me:   ": "pre me:   ",
	// "pre cmp:   ": "",
	// "cmp:   ": "cmp:   ",
	// "sub cmp:   ": "",
	// "last predictor count:   ": "",
	// "gop size:   ": "tamaño gop:   ",
	// "qcompress:   ": "",
	// "qblur:   ": "",
	// "subq:   ": "",
	// "framerefs:   ": "",
	// "me method:   ": "Metodo me   ",
	// "mb decision:   ": "mb desición   ",
	// "max B frames:   ": "",
	// "num threads:   ": "",
	// "audio codec values": "valores de codec de audio",
	// "sample format:   ": "",
	// "Rate Control Mode:": "Controles de la imagen",
	// "CBR": "",
	// "VBR": "",
	// "Constant QP": "",
	// "Rate Control Mode flags:": "",
	// "Temporal Scale Mode:": "",
	// "Spatial Scale Mode:": "",
	// "Frame Interval (100ns units):": "",
	// "Bit Rate:": "media de bits:   ",
	// "Hints:": "",
	// "Resolution": "Resolución:",
	// "Profile": "",
	// "Rate Control": "Controles de la imagen",
	// "Usage Type": "",
	// "Slice Mode": "",
	// "Slice Unit": "",
	// "MVC View": "",
	// "Temporal Scale": "",
	// "SNR Scale": "",
	// "Spatial Scale": "",
	// "Spatial Layer Ratio": "",
	// "Frame Interval": "FPS:",
	// "Leaky Bucket Size": "",
	// "Bit Rate": "",
	// "CABAC": "",
	// "(I) Frame Period": "",
	// "Slice Mode:": "",
	// "no multiple slices": "",
	// "bits/slice": "",
	// "Mbits/slice": "",
	// "slices/frame": "",
	// "Slice Units:": "",
	// "Profile:": "",
	// "Baseline Profile": "",
	// "Main Profile": "",
	// "High Profile": "",
	// "Scalable Baseline Profile": "",
	// "Scalable High Profile": "",
	// "Multiview High Profile": "",
	// "Stereo High Profile": "",
	// "Profile flags:": "",
	// "(I) Frame Period (ms):": "",
	// "Estimated Video Delay (ms):": "",
	// "Estimated Max Config Delay (ms):": "",
	// "Usage Type:": "",
	// "Real-time": "",
	// "Broadcast": "",
	// "Storage": "",
	// "(0) Non-scalable single layer AVC": "",
	// "(1) SVC temporal scalability with hierarchical P": "",
	// "(2q) SVC temporal scalability + Quality/SNR scalability": "",
	// "(2s) SVC temporal scalability + spatial scalability": "",
	// "(3) Full SVC scalability": "",
	// "SNR Control Mode:": "",
	// "No SNR Enhancement Layer": "",
	// "CGS NonRewrite (2 Layer)": "",
	// "CGS NonRewrite (3 Layer)": "",
	// "CGS Rewrite (2 Layer)": "",
	// "CGS Rewrite (3 Layer)": "",
	// "MGS (2 Layer)": "",
	// "Stream Mux Enable": "",
	// "Embed H.264 aux stream": "",
	// "Embed YUY2 aux stream": "",
	// "Embed NV12 aux stream": "",
	// "MJPG payload container": "",
	// "Stream Format:": "",
	// "Byte stream format (H.264 Annex-B)": "",
	// "NAL stream format": "AVI - formato avi",
	// "Entropy CABAC:": "",
	// "CAVLC": "",
	// "Picture timing SEI": "",
	// "B Frames:": "FPS:",
	// "Preview Flipped": "",
	// "Additional MVC Views:": "",
	// "Simulcast stream index:": "",
	// "Spatial Layer Ratio:": "",
	// "Leaky Bucket Size (ms):": "",
	// "Encoder Reset": "Rotación (reajuste)",
	// "COMMIT": "",
	// "Settings": "",
	// "Hardware Defaults": "",
	// "Camera Button": "",
	// "Capture Image": "",
	// "Capture Video": "",
	// "Photo": "",
	// "File": "",
	// "Increment Filename": "",
	// "Video": "",
	// "Video Codec": "",
	// "Video Codec Properties": "",
	// "Audio Codec": "",
	// "Audio Codec Properties": "",
	// "Left": "Izquierda",
	// "Right": "Derecha",
	// "Down": "Abajo",
	// "Up": "Arriba",
	// "8 bit": "8 bit",
	// "12 bit": "12 bit",
	// "Auto Focus (continuous)": "Foco Automatico (continuo)",
	// "set Focus": "Focar",
	// "_Apply": "Aplicar",
	// "Frame Rate:": "FPS:",
	// "Resolution:": "Resolución:",
	// "Camera Output:": "Salida de la cámara:",
	// "---- Video Filters ----": "---- Filtros Video ----",
	// " Mirror": " Espejo",
	// " Invert": " Invertido",
	// " Negative": " Negativo",
	// " Mono": " Gris",
	// " Pieces": " Pedazos",
	// " Particles": " Partículas",
	// "Print help": "",
	// "Print version": "Imprimir versión",
	// "LEVEL": "",
	// "Set Verbosity level (def: 0)": "",
	// "DEVICE": "",
	// "Set device name (def: /dev/video0)": "Dispositivo de video [pred: /dev/video0]",
	// "METHOD": "",
	// "Set capture method [read | mmap (def)]": "Método de captura (1-mmap (predeterminado) 2-read)",
	// "WIDTHxHEIGHT": "",
	// "Request resolution (e.g 640x480)": "",
	// "FOURCC": "",
	// "Request format (e.g MJPG)": "",
	// "RENDER_API": "",
	// "Select render API (e.g none; sdl)": "",
	// "AUDIO_API": "",
	// "Select audio API (e.g none; port; pulse)": "",
	// "AUDIO_DEVICE": "",
	// "Select audio device index for selected api (0..N)": "",
	// "GUI_API": "",
	// "Select GUI API (e.g none; gtk3)": "",
	// "CODEC": "",
	// "Audio codec [pcm mp2 mp3 aac ac3 vorb]": "",
	// "Video codec [raw mjpg mpeg flv1 wmv1 mpg2 mp43 dx50 h264 vp80 theo]": "",
	// "FILENAME": "",
	// "load control profile": "",
	// "filename for captured video)": "",
	// "filename for captured image)": "",
	// "TIME_IN_SEC": "",
	// "time (double) in sec. for video capture)": "",
	// "time (double) in sec. between captured photos)": "",
	// "TOTAL": "",
	// "total number of captured photos)": "",
	// "Start in control panel mode": "",
	// "Guvcview version %s\n\n": "Aviso de Guvcview:",
	// "Usage:\n   guvcview [OPTIONS]\n\n": "",
	// "OPTIONS:\n": "",
	// "saving video to %s": "",
	// "saving image to %s": ""
};

export default Translation;
